/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetReviewInfoWithCustomerResultListResultCustomModel } from '../../models/get-review-info-with-customer-result-list-result-custom-model';

export interface ApiReviewListCustomersGet$Plain$Params {
}

export function apiReviewListCustomersGet$Plain(http: HttpClient, rootUrl: string, params?: ApiReviewListCustomersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GetReviewInfoWithCustomerResultListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiReviewListCustomersGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetReviewInfoWithCustomerResultListResultCustomModel>;
    })
  );
}

apiReviewListCustomersGet$Plain.PATH = '/api/Review/ListCustomers';
