/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewListResultCustomModel } from '../../models/review-list-result-custom-model';

export interface ApiReviewListReviewGet$Plain$Params {
}

export function apiReviewListReviewGet$Plain(http: HttpClient, rootUrl: string, params?: ApiReviewListReviewGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiReviewListReviewGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewListResultCustomModel>;
    })
  );
}

apiReviewListReviewGet$Plain.PATH = '/api/Review/ListReview';
