/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewResponseListResultCustomModel } from '../../models/review-response-list-result-custom-model';

export interface ApiReviewGetReviewsByProductIdProductIdGet$Json$Params {
  productId: number;
}

export function apiReviewGetReviewsByProductIdProductIdGet$Json(http: HttpClient, rootUrl: string, params: ApiReviewGetReviewsByProductIdProductIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiReviewGetReviewsByProductIdProductIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewResponseListResultCustomModel>;
    })
  );
}

apiReviewGetReviewsByProductIdProductIdGet$Json.PATH = '/api/Review/GetReviewsByProductId/{productId}';
