/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadFileModelResultCustomModel } from '../../models/upload-file-model-result-custom-model';

export interface ApiUploadUploadPost$Plain$Params {
}

export function apiUploadUploadPost$Plain(http: HttpClient, rootUrl: string, params?: ApiUploadUploadPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadFileModelResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiUploadUploadPost$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadFileModelResultCustomModel>;
    })
  );
}

apiUploadUploadPost$Plain.PATH = '/api/Upload/Upload';
