/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerResponseResultCustomModel } from '../../models/customer-response-result-custom-model';

export interface ApiCustomerGetCustomerByIdGet$Json$Params {
  customerId?: number;
}

export function apiCustomerGetCustomerByIdGet$Json(http: HttpClient, rootUrl: string, params?: ApiCustomerGetCustomerByIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiCustomerGetCustomerByIdGet$Json.PATH, 'get');
  if (params) {
    rb.query('customerId', params.customerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerResponseResultCustomModel>;
    })
  );
}

apiCustomerGetCustomerByIdGet$Json.PATH = '/api/Customer/GetCustomerById';
