/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StringResultCustomModel } from '../../models/string-result-custom-model';

export interface ApiCustomerResetPasswordResetPasswordPost$Json$Params {
  otp?: string;
  newPassword?: string;
}

export function apiCustomerResetPasswordResetPasswordPost$Json(http: HttpClient, rootUrl: string, params?: ApiCustomerResetPasswordResetPasswordPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiCustomerResetPasswordResetPasswordPost$Json.PATH, 'post');
  if (params) {
    rb.query('otp', params.otp, {});
    rb.query('newPassword', params.newPassword, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringResultCustomModel>;
    })
  );
}

apiCustomerResetPasswordResetPasswordPost$Json.PATH = '/api/Customer/ResetPassword/ResetPassword';
