/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryListResultCustomModel } from '../../models/category-list-result-custom-model';

export interface ApiCategoryGetAllGet$Json$Params {
}

export function apiCategoryGetAllGet$Json(http: HttpClient, rootUrl: string, params?: ApiCategoryGetAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiCategoryGetAllGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryListResultCustomModel>;
    })
  );
}

apiCategoryGetAllGet$Json.PATH = '/api/Category/GetAll';
