/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResultCustomModel } from '../../models/category-result-custom-model';

export interface ApiCategoryGetByIdCategoryIdGet$Plain$Params {
  categoryId: number;
}

export function apiCategoryGetByIdCategoryIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCategoryGetByIdCategoryIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiCategoryGetByIdCategoryIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('categoryId', params.categoryId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryResultCustomModel>;
    })
  );
}

apiCategoryGetByIdCategoryIdGet$Plain.PATH = '/api/Category/GetById/{categoryId}';
