/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserListResultCustomModel } from '../../models/user-list-result-custom-model';

export interface ApiUserListUserGet$Plain$Params {
}

export function apiUserListUserGet$Plain(http: HttpClient, rootUrl: string, params?: ApiUserListUserGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiUserListUserGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserListResultCustomModel>;
    })
  );
}

apiUserListUserGet$Plain.PATH = '/api/User/ListUser';
