/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUserRequest } from '../../models/update-user-request';
import { UpdateUserResponseResultCustomModel } from '../../models/update-user-response-result-custom-model';

export interface ApiUserUpdateUserPut$Json$Params {
      body?: UpdateUserRequest
}

export function apiUserUpdateUserPut$Json(http: HttpClient, rootUrl: string, params?: ApiUserUpdateUserPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateUserResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiUserUpdateUserPut$Json.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateUserResponseResultCustomModel>;
    })
  );
}

apiUserUpdateUserPut$Json.PATH = '/api/User/UpdateUser';
