/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUserResponseListResultCustomModel } from '../../models/update-user-response-list-result-custom-model';

export interface ApiUserListUserGet$Json$Params {
}

export function apiUserListUserGet$Json(http: HttpClient, rootUrl: string, params?: ApiUserListUserGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateUserResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiUserListUserGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateUserResponseListResultCustomModel>;
    })
  );
}

apiUserListUserGet$Json.PATH = '/api/User/ListUser';
