/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaptureOrderResponseResultCustomModel } from '../../models/capture-order-response-result-custom-model';

export interface ApiPayPalCaptureOrderOrderIdPost$Json$Params {
  orderId: string;
}

export function apiPayPalCaptureOrderOrderIdPost$Json(http: HttpClient, rootUrl: string, params: ApiPayPalCaptureOrderOrderIdPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CaptureOrderResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiPayPalCaptureOrderOrderIdPost$Json.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaptureOrderResponseResultCustomModel>;
    })
  );
}

apiPayPalCaptureOrderOrderIdPost$Json.PATH = '/api/PayPal/capture-order/{orderId}';
