/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  address?: string | null;
  avatar?: string | null;
  birthday?: string | null;
  email?: string | null;
  fullname?: string | null;
  listRoles?: Array<number> | null;
  password?: string | null;
  phone?: string | null;
  position?: string | null;
  username?: string | null;
}
