/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderDto {
  amount?: number;
  cancelUrl?: string | null;
  orderId?: string | null;
  returnUrl?: string | null;
}
