/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderRequest {
  createOn?: string;
  customerId?: number;
  note?: string | null;
  promotionId?: number | null;
  state?: number;
  totalAmount?: number;
  userId?: number;
}
