/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerResponse {
  address?: string | null;
  customerId?: number;
  email?: string | null;
  fullname?: string | null;
  isActive?: boolean | null;
  phone?: string | null;
}
