/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerRequest {
  address?: string | null;
  email?: string | null;
  fullName?: string | null;
  password?: string | null;
  phone?: string | null;
  username?: string | null;
}
