/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GetDetailProductOrderSpResult } from '../models/get-detail-product-order-sp-result';
export interface DetailOrderReponse {
  address?: string | null;
  detailProducts?: Array<GetDetailProductOrderSpResult> | null;
  nameCustomer?: string | null;
  stateId?: number;
}
