/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginResponse {
  address?: string | null;
  avatar?: string | null;
  birthday?: string | null;
  createOn?: string;
  email?: string | null;
  fullname?: string | null;
  phone?: string | null;
  role?: Array<string> | null;
  roleName?: string | null;
  token?: string | null;
  userId?: number;
  username?: string | null;
}
