/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
import { ProductOrder } from '../models/product-order';
import { User } from '../models/user';
export interface Order {
  createOn?: string;
  customer?: Customer;
  customerId?: number;
  note?: string | null;
  orderId?: number;
  productOrders?: Array<ProductOrder> | null;
  state?: number;
  user?: User;
  userId?: number;
}
