/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Order } from '../models/order';
import { Product } from '../models/product';
export interface ProductOrder {
  order?: Order;
  orderId?: number;
  priceInput?: number;
  priceOutput?: number;
  product?: Product;
  productId?: number;
  productOrderId?: number;
  quantity?: number;
  saleOff?: number;
}
