/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PromotionResponse {
  creationDate?: string;
  description?: string | null;
  discountAmount?: number;
  endDate?: string;
  finalAmount?: number;
  isActive?: boolean;
  minimumPurchaseAmount?: number;
  orderId?: number | null;
  programName?: string | null;
  promotionCode?: string | null;
  startDate?: string;
  usageLimit?: number | null;
}
