/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewRequest {
  comment?: string | null;
  customerId?: number;
  productId?: number;
  reviewId?: number;
}
