/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponse {
  comment?: string | null;
  productId?: number;
  reviewId?: number;
}
