/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface Role {
  name?: string | null;
  roleId?: number;
  userRoles?: Array<UserRole> | null;
}
