/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserResponse {
  address?: string | null;
  avatar?: string | null;
  birthday?: string | null;
  email?: string | null;
  fullname?: string | null;
  phone?: string | null;
  userId?: number;
  username?: string | null;
}
