/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductRequest {
  categoryId?: number;
  description?: string | null;
  name?: string | null;
  priceOutput?: number;
  productId?: number;
  quantity?: number;
}
