/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {
  address?: string | null;
  birthday?: string | null;
  email?: string | null;
  fullname?: string | null;
  isActive?: boolean | null;
  listRoles?: Array<number> | null;
  phone?: string | null;
  userId?: number;
}
