/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductReponse {
  categoryId?: number;
  description?: string | null;
  img?: string | null;
  listCategorys?: Array<number> | null;
  name?: string | null;
  priceOutput?: number;
  quantity?: number;
}
