/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadFileModel {
  isImage?: boolean | null;
  originalName?: string | null;
  pathSave?: string | null;
  url?: string | null;
}
