/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Order } from '../models/order';
import { UserRole } from '../models/user-role';
export interface User {
  address?: string | null;
  avatar?: string | null;
  birthday?: string | null;
  createOn?: string;
  email?: string | null;
  fullname?: string | null;
  isActive?: boolean | null;
  orders?: Array<Order> | null;
  password?: string | null;
  phone?: string | null;
  position?: string | null;
  userId?: number;
  userRoles?: Array<UserRole> | null;
  username?: string | null;
}
