/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
import { User } from '../models/user';
export interface UserRole {
  role?: Role;
  roleId?: number;
  user?: User;
  userId?: number;
  userRoleId?: number;
}
