/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  address?: string | null;
  avatar?: string | null;
  birthday?: string | null;
  createOn?: string;
  email?: string | null;
  fullname?: string | null;
  isActive?: boolean | null;
  lstRolesId?: Array<number> | null;
  phone?: string | null;
  position?: string | null;
  userId?: number;
  username?: string | null;
}
