/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCategoryCreatePost$Json } from '../fn/category/api-category-create-post-json';
import { ApiCategoryCreatePost$Json$Params } from '../fn/category/api-category-create-post-json';
import { apiCategoryCreatePost$Plain } from '../fn/category/api-category-create-post-plain';
import { ApiCategoryCreatePost$Plain$Params } from '../fn/category/api-category-create-post-plain';
import { apiCategoryDeleteCategoryIdDelete$Json } from '../fn/category/api-category-delete-category-id-delete-json';
import { ApiCategoryDeleteCategoryIdDelete$Json$Params } from '../fn/category/api-category-delete-category-id-delete-json';
import { apiCategoryDeleteCategoryIdDelete$Plain } from '../fn/category/api-category-delete-category-id-delete-plain';
import { ApiCategoryDeleteCategoryIdDelete$Plain$Params } from '../fn/category/api-category-delete-category-id-delete-plain';
import { apiCategoryGetAllGet$Json } from '../fn/category/api-category-get-all-get-json';
import { ApiCategoryGetAllGet$Json$Params } from '../fn/category/api-category-get-all-get-json';
import { apiCategoryGetAllGet$Plain } from '../fn/category/api-category-get-all-get-plain';
import { ApiCategoryGetAllGet$Plain$Params } from '../fn/category/api-category-get-all-get-plain';
import { apiCategoryGetByIdCategoryIdGet$Json } from '../fn/category/api-category-get-by-id-category-id-get-json';
import { ApiCategoryGetByIdCategoryIdGet$Json$Params } from '../fn/category/api-category-get-by-id-category-id-get-json';
import { apiCategoryGetByIdCategoryIdGet$Plain } from '../fn/category/api-category-get-by-id-category-id-get-plain';
import { ApiCategoryGetByIdCategoryIdGet$Plain$Params } from '../fn/category/api-category-get-by-id-category-id-get-plain';
import { apiCategoryUpdatePut$Json } from '../fn/category/api-category-update-put-json';
import { ApiCategoryUpdatePut$Json$Params } from '../fn/category/api-category-update-put-json';
import { apiCategoryUpdatePut$Plain } from '../fn/category/api-category-update-put-plain';
import { ApiCategoryUpdatePut$Plain$Params } from '../fn/category/api-category-update-put-plain';
import { BooleanResultCustomModel } from '../models/boolean-result-custom-model';
import { CategoryListResultCustomModel } from '../models/category-list-result-custom-model';
import { CategoryResultCustomModel } from '../models/category-result-custom-model';

@Injectable({ providedIn: 'root' })
export class CategoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCategoryGetAllGet()` */
  static readonly ApiCategoryGetAllGetPath = '/api/Category/GetAll';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryGetAllGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetAllGet$Plain$Response(params?: ApiCategoryGetAllGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryListResultCustomModel>> {
    return apiCategoryGetAllGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryGetAllGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetAllGet$Plain(params?: ApiCategoryGetAllGet$Plain$Params, context?: HttpContext): Observable<CategoryListResultCustomModel> {
    return this.apiCategoryGetAllGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryListResultCustomModel>): CategoryListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryGetAllGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetAllGet$Json$Response(params?: ApiCategoryGetAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryListResultCustomModel>> {
    return apiCategoryGetAllGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryGetAllGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetAllGet$Json(params?: ApiCategoryGetAllGet$Json$Params, context?: HttpContext): Observable<CategoryListResultCustomModel> {
    return this.apiCategoryGetAllGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryListResultCustomModel>): CategoryListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiCategoryGetByIdCategoryIdGet()` */
  static readonly ApiCategoryGetByIdCategoryIdGetPath = '/api/Category/GetById/{categoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryGetByIdCategoryIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetByIdCategoryIdGet$Plain$Response(params: ApiCategoryGetByIdCategoryIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResultCustomModel>> {
    return apiCategoryGetByIdCategoryIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryGetByIdCategoryIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetByIdCategoryIdGet$Plain(params: ApiCategoryGetByIdCategoryIdGet$Plain$Params, context?: HttpContext): Observable<CategoryResultCustomModel> {
    return this.apiCategoryGetByIdCategoryIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResultCustomModel>): CategoryResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryGetByIdCategoryIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetByIdCategoryIdGet$Json$Response(params: ApiCategoryGetByIdCategoryIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResultCustomModel>> {
    return apiCategoryGetByIdCategoryIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryGetByIdCategoryIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryGetByIdCategoryIdGet$Json(params: ApiCategoryGetByIdCategoryIdGet$Json$Params, context?: HttpContext): Observable<CategoryResultCustomModel> {
    return this.apiCategoryGetByIdCategoryIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResultCustomModel>): CategoryResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiCategoryDeleteCategoryIdDelete()` */
  static readonly ApiCategoryDeleteCategoryIdDeletePath = '/api/Category/Delete/{categoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryDeleteCategoryIdDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryDeleteCategoryIdDelete$Plain$Response(params: ApiCategoryDeleteCategoryIdDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryDeleteCategoryIdDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryDeleteCategoryIdDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryDeleteCategoryIdDelete$Plain(params: ApiCategoryDeleteCategoryIdDelete$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryDeleteCategoryIdDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryDeleteCategoryIdDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryDeleteCategoryIdDelete$Json$Response(params: ApiCategoryDeleteCategoryIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryDeleteCategoryIdDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryDeleteCategoryIdDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCategoryDeleteCategoryIdDelete$Json(params: ApiCategoryDeleteCategoryIdDelete$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryDeleteCategoryIdDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiCategoryUpdatePut()` */
  static readonly ApiCategoryUpdatePutPath = '/api/Category/Update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryUpdatePut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryUpdatePut$Plain$Response(params?: ApiCategoryUpdatePut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryUpdatePut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryUpdatePut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryUpdatePut$Plain(params?: ApiCategoryUpdatePut$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryUpdatePut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryUpdatePut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryUpdatePut$Json$Response(params?: ApiCategoryUpdatePut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryUpdatePut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryUpdatePut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryUpdatePut$Json(params?: ApiCategoryUpdatePut$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryUpdatePut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiCategoryCreatePost()` */
  static readonly ApiCategoryCreatePostPath = '/api/Category/Create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryCreatePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryCreatePost$Plain$Response(params?: ApiCategoryCreatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryCreatePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryCreatePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryCreatePost$Plain(params?: ApiCategoryCreatePost$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryCreatePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCategoryCreatePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryCreatePost$Json$Response(params?: ApiCategoryCreatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiCategoryCreatePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCategoryCreatePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCategoryCreatePost$Json(params?: ApiCategoryCreatePost$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiCategoryCreatePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

}
