/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiExportExportGet } from '../fn/export/api-export-export-get';
import { ApiExportExportGet$Params } from '../fn/export/api-export-export-get';

@Injectable({ providedIn: 'root' })
export class ExportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiExportExportGet()` */
  static readonly ApiExportExportGetPath = '/api/Export/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiExportExportGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiExportExportGet$Response(params?: ApiExportExportGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiExportExportGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiExportExportGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiExportExportGet(params?: ApiExportExportGet$Params, context?: HttpContext): Observable<void> {
    return this.apiExportExportGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
