/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiOrderCreatePost$Json } from '../fn/order/api-order-create-post-json';
import { ApiOrderCreatePost$Json$Params } from '../fn/order/api-order-create-post-json';
import { apiOrderCreatePost$Plain } from '../fn/order/api-order-create-post-plain';
import { ApiOrderCreatePost$Plain$Params } from '../fn/order/api-order-create-post-plain';
import { apiOrderGetOrderByIdGet$Json } from '../fn/order/api-order-get-order-by-id-get-json';
import { ApiOrderGetOrderByIdGet$Json$Params } from '../fn/order/api-order-get-order-by-id-get-json';
import { apiOrderGetOrderByIdGet$Plain } from '../fn/order/api-order-get-order-by-id-get-plain';
import { ApiOrderGetOrderByIdGet$Plain$Params } from '../fn/order/api-order-get-order-by-id-get-plain';
import { apiOrderListOrderGet$Json } from '../fn/order/api-order-list-order-get-json';
import { ApiOrderListOrderGet$Json$Params } from '../fn/order/api-order-list-order-get-json';
import { apiOrderListOrderGet$Plain } from '../fn/order/api-order-list-order-get-plain';
import { ApiOrderListOrderGet$Plain$Params } from '../fn/order/api-order-list-order-get-plain';
import { BooleanResultCustomModel } from '../models/boolean-result-custom-model';
import { OrderReponseListResultCustomModel } from '../models/order-reponse-list-result-custom-model';
import { OrderReponseResultCustomModel } from '../models/order-reponse-result-custom-model';

@Injectable({ providedIn: 'root' })
export class OrderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiOrderCreatePost()` */
  static readonly ApiOrderCreatePostPath = '/api/Order/Create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain$Response(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderCreatePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderCreatePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json$Response(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderCreatePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderCreatePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderListOrderGet()` */
  static readonly ApiOrderListOrderGetPath = '/api/Order/ListOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Plain$Response(params?: ApiOrderListOrderGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseListResultCustomModel>> {
    return apiOrderListOrderGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Plain(params?: ApiOrderListOrderGet$Plain$Params, context?: HttpContext): Observable<OrderReponseListResultCustomModel> {
    return this.apiOrderListOrderGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseListResultCustomModel>): OrderReponseListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Json$Response(params?: ApiOrderListOrderGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseListResultCustomModel>> {
    return apiOrderListOrderGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Json(params?: ApiOrderListOrderGet$Json$Params, context?: HttpContext): Observable<OrderReponseListResultCustomModel> {
    return this.apiOrderListOrderGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseListResultCustomModel>): OrderReponseListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetOrderByIdGet()` */
  static readonly ApiOrderGetOrderByIdGetPath = '/api/Order/GetOrderById';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain$Response(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json$Response(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

}
