/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiOrderChangeStateOrderPost$Json } from '../fn/order/api-order-change-state-order-post-json';
import { ApiOrderChangeStateOrderPost$Json$Params } from '../fn/order/api-order-change-state-order-post-json';
import { apiOrderChangeStateOrderPost$Plain } from '../fn/order/api-order-change-state-order-post-plain';
import { ApiOrderChangeStateOrderPost$Plain$Params } from '../fn/order/api-order-change-state-order-post-plain';
import { apiOrderCreatePost$Json } from '../fn/order/api-order-create-post-json';
import { ApiOrderCreatePost$Json$Params } from '../fn/order/api-order-create-post-json';
import { apiOrderCreatePost$Plain } from '../fn/order/api-order-create-post-plain';
import { ApiOrderCreatePost$Plain$Params } from '../fn/order/api-order-create-post-plain';
import { apiOrderGetOrderByIdGet$Json } from '../fn/order/api-order-get-order-by-id-get-json';
import { ApiOrderGetOrderByIdGet$Json$Params } from '../fn/order/api-order-get-order-by-id-get-json';
import { apiOrderGetOrderByIdGet$Plain } from '../fn/order/api-order-get-order-by-id-get-plain';
import { ApiOrderGetOrderByIdGet$Plain$Params } from '../fn/order/api-order-get-order-by-id-get-plain';
import { apiOrderGetRevenueLast7DaysGet$Json } from '../fn/order/api-order-get-revenue-last-7-days-get-json';
import { ApiOrderGetRevenueLast7DaysGet$Json$Params } from '../fn/order/api-order-get-revenue-last-7-days-get-json';
import { apiOrderGetRevenueLast7DaysGet$Plain } from '../fn/order/api-order-get-revenue-last-7-days-get-plain';
import { ApiOrderGetRevenueLast7DaysGet$Plain$Params } from '../fn/order/api-order-get-revenue-last-7-days-get-plain';
import { apiOrderGetTotalOrdersTotalOrdersGet$Json } from '../fn/order/api-order-get-total-orders-total-orders-get-json';
import { ApiOrderGetTotalOrdersTotalOrdersGet$Json$Params } from '../fn/order/api-order-get-total-orders-total-orders-get-json';
import { apiOrderGetTotalOrdersTotalOrdersGet$Plain } from '../fn/order/api-order-get-total-orders-total-orders-get-plain';
import { ApiOrderGetTotalOrdersTotalOrdersGet$Plain$Params } from '../fn/order/api-order-get-total-orders-total-orders-get-plain';
import { apiOrderListDetailOrderGet$Json } from '../fn/order/api-order-list-detail-order-get-json';
import { ApiOrderListDetailOrderGet$Json$Params } from '../fn/order/api-order-list-detail-order-get-json';
import { apiOrderListDetailOrderGet$Plain } from '../fn/order/api-order-list-detail-order-get-plain';
import { ApiOrderListDetailOrderGet$Plain$Params } from '../fn/order/api-order-list-detail-order-get-plain';
import { apiOrderListOrderByCustomerIdGet$Json } from '../fn/order/api-order-list-order-by-customer-id-get-json';
import { ApiOrderListOrderByCustomerIdGet$Json$Params } from '../fn/order/api-order-list-order-by-customer-id-get-json';
import { apiOrderListOrderByCustomerIdGet$Plain } from '../fn/order/api-order-list-order-by-customer-id-get-plain';
import { ApiOrderListOrderByCustomerIdGet$Plain$Params } from '../fn/order/api-order-list-order-by-customer-id-get-plain';
import { apiOrderListOrderGet$Json } from '../fn/order/api-order-list-order-get-json';
import { ApiOrderListOrderGet$Json$Params } from '../fn/order/api-order-list-order-get-json';
import { apiOrderListOrderGet$Plain } from '../fn/order/api-order-list-order-get-plain';
import { ApiOrderListOrderGet$Plain$Params } from '../fn/order/api-order-list-order-get-plain';
import { BooleanResultCustomModel } from '../models/boolean-result-custom-model';
import { DetailOrderReponseResultCustomModel } from '../models/detail-order-reponse-result-custom-model';
import { GetListOrderByCustomerIdSpResultListResultCustomModel } from '../models/get-list-order-by-customer-id-sp-result-list-result-custom-model';
import { GetListOrderSpResultListResultCustomModel } from '../models/get-list-order-sp-result-list-result-custom-model';
import { Int32ResultCustomModel } from '../models/int-32-result-custom-model';
import { OrderReponseResultCustomModel } from '../models/order-reponse-result-custom-model';
import { RevenueResponseListResultCustomModel } from '../models/revenue-response-list-result-custom-model';

@Injectable({ providedIn: 'root' })
export class OrderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiOrderCreatePost()` */
  static readonly ApiOrderCreatePostPath = '/api/Order/Create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain$Response(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ResultCustomModel>> {
    return apiOrderCreatePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<Int32ResultCustomModel> {
    return this.apiOrderCreatePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ResultCustomModel>): Int32ResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json$Response(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ResultCustomModel>> {
    return apiOrderCreatePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<Int32ResultCustomModel> {
    return this.apiOrderCreatePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ResultCustomModel>): Int32ResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderListOrderGet()` */
  static readonly ApiOrderListOrderGetPath = '/api/Order/ListOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Plain$Response(params?: ApiOrderListOrderGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListOrderSpResultListResultCustomModel>> {
    return apiOrderListOrderGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Plain(params?: ApiOrderListOrderGet$Plain$Params, context?: HttpContext): Observable<GetListOrderSpResultListResultCustomModel> {
    return this.apiOrderListOrderGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetListOrderSpResultListResultCustomModel>): GetListOrderSpResultListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Json$Response(params?: ApiOrderListOrderGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListOrderSpResultListResultCustomModel>> {
    return apiOrderListOrderGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderGet$Json(params?: ApiOrderListOrderGet$Json$Params, context?: HttpContext): Observable<GetListOrderSpResultListResultCustomModel> {
    return this.apiOrderListOrderGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetListOrderSpResultListResultCustomModel>): GetListOrderSpResultListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderListOrderByCustomerIdGet()` */
  static readonly ApiOrderListOrderByCustomerIdGetPath = '/api/Order/ListOrderByCustomerId';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderByCustomerIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderByCustomerIdGet$Plain$Response(params?: ApiOrderListOrderByCustomerIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListOrderByCustomerIdSpResultListResultCustomModel>> {
    return apiOrderListOrderByCustomerIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderByCustomerIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderByCustomerIdGet$Plain(params?: ApiOrderListOrderByCustomerIdGet$Plain$Params, context?: HttpContext): Observable<GetListOrderByCustomerIdSpResultListResultCustomModel> {
    return this.apiOrderListOrderByCustomerIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetListOrderByCustomerIdSpResultListResultCustomModel>): GetListOrderByCustomerIdSpResultListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListOrderByCustomerIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderByCustomerIdGet$Json$Response(params?: ApiOrderListOrderByCustomerIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListOrderByCustomerIdSpResultListResultCustomModel>> {
    return apiOrderListOrderByCustomerIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListOrderByCustomerIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListOrderByCustomerIdGet$Json(params?: ApiOrderListOrderByCustomerIdGet$Json$Params, context?: HttpContext): Observable<GetListOrderByCustomerIdSpResultListResultCustomModel> {
    return this.apiOrderListOrderByCustomerIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetListOrderByCustomerIdSpResultListResultCustomModel>): GetListOrderByCustomerIdSpResultListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderListDetailOrderGet()` */
  static readonly ApiOrderListDetailOrderGetPath = '/api/Order/ListDetailOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListDetailOrderGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListDetailOrderGet$Plain$Response(params?: ApiOrderListDetailOrderGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DetailOrderReponseResultCustomModel>> {
    return apiOrderListDetailOrderGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListDetailOrderGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListDetailOrderGet$Plain(params?: ApiOrderListDetailOrderGet$Plain$Params, context?: HttpContext): Observable<DetailOrderReponseResultCustomModel> {
    return this.apiOrderListDetailOrderGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DetailOrderReponseResultCustomModel>): DetailOrderReponseResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderListDetailOrderGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListDetailOrderGet$Json$Response(params?: ApiOrderListDetailOrderGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DetailOrderReponseResultCustomModel>> {
    return apiOrderListDetailOrderGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderListDetailOrderGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderListDetailOrderGet$Json(params?: ApiOrderListDetailOrderGet$Json$Params, context?: HttpContext): Observable<DetailOrderReponseResultCustomModel> {
    return this.apiOrderListDetailOrderGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DetailOrderReponseResultCustomModel>): DetailOrderReponseResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetOrderByIdGet()` */
  static readonly ApiOrderGetOrderByIdGetPath = '/api/Order/GetOrderById';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain$Response(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json$Response(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderChangeStateOrderPost()` */
  static readonly ApiOrderChangeStateOrderPostPath = '/api/Order/ChangeStateOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderChangeStateOrderPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Plain$Response(params?: ApiOrderChangeStateOrderPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderChangeStateOrderPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderChangeStateOrderPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Plain(params?: ApiOrderChangeStateOrderPost$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderChangeStateOrderPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderChangeStateOrderPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Json$Response(params?: ApiOrderChangeStateOrderPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderChangeStateOrderPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderChangeStateOrderPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Json(params?: ApiOrderChangeStateOrderPost$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderChangeStateOrderPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetRevenueLast7DaysGet()` */
  static readonly ApiOrderGetRevenueLast7DaysGetPath = '/api/Order/GetRevenueLast7Days';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetRevenueLast7DaysGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Plain$Response(params?: ApiOrderGetRevenueLast7DaysGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RevenueResponseListResultCustomModel>> {
    return apiOrderGetRevenueLast7DaysGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetRevenueLast7DaysGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Plain(params?: ApiOrderGetRevenueLast7DaysGet$Plain$Params, context?: HttpContext): Observable<RevenueResponseListResultCustomModel> {
    return this.apiOrderGetRevenueLast7DaysGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<RevenueResponseListResultCustomModel>): RevenueResponseListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetRevenueLast7DaysGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Json$Response(params?: ApiOrderGetRevenueLast7DaysGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RevenueResponseListResultCustomModel>> {
    return apiOrderGetRevenueLast7DaysGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetRevenueLast7DaysGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Json(params?: ApiOrderGetRevenueLast7DaysGet$Json$Params, context?: HttpContext): Observable<RevenueResponseListResultCustomModel> {
    return this.apiOrderGetRevenueLast7DaysGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<RevenueResponseListResultCustomModel>): RevenueResponseListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetTotalOrdersTotalOrdersGet()` */
  static readonly ApiOrderGetTotalOrdersTotalOrdersGetPath = '/api/Order/GetTotalOrders/total-orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetTotalOrdersTotalOrdersGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetTotalOrdersTotalOrdersGet$Plain$Response(params?: ApiOrderGetTotalOrdersTotalOrdersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ResultCustomModel>> {
    return apiOrderGetTotalOrdersTotalOrdersGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetTotalOrdersTotalOrdersGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetTotalOrdersTotalOrdersGet$Plain(params?: ApiOrderGetTotalOrdersTotalOrdersGet$Plain$Params, context?: HttpContext): Observable<Int32ResultCustomModel> {
    return this.apiOrderGetTotalOrdersTotalOrdersGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ResultCustomModel>): Int32ResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetTotalOrdersTotalOrdersGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetTotalOrdersTotalOrdersGet$Json$Response(params?: ApiOrderGetTotalOrdersTotalOrdersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ResultCustomModel>> {
    return apiOrderGetTotalOrdersTotalOrdersGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetTotalOrdersTotalOrdersGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetTotalOrdersTotalOrdersGet$Json(params?: ApiOrderGetTotalOrdersTotalOrdersGet$Json$Params, context?: HttpContext): Observable<Int32ResultCustomModel> {
    return this.apiOrderGetTotalOrdersTotalOrdersGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ResultCustomModel>): Int32ResultCustomModel => r.body)
    );
  }

}
