/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUploadUploadPost$Json } from '../fn/upload/api-upload-upload-post-json';
import { ApiUploadUploadPost$Json$Params } from '../fn/upload/api-upload-upload-post-json';
import { apiUploadUploadPost$Plain } from '../fn/upload/api-upload-upload-post-plain';
import { ApiUploadUploadPost$Plain$Params } from '../fn/upload/api-upload-upload-post-plain';
import { UploadFileModelResultCustomModel } from '../models/upload-file-model-result-custom-model';

@Injectable({ providedIn: 'root' })
export class UploadService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUploadUploadPost()` */
  static readonly ApiUploadUploadPostPath = '/api/Upload/Upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUploadUploadPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUploadUploadPost$Plain$Response(params?: ApiUploadUploadPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadFileModelResultCustomModel>> {
    return apiUploadUploadPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUploadUploadPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUploadUploadPost$Plain(params?: ApiUploadUploadPost$Plain$Params, context?: HttpContext): Observable<UploadFileModelResultCustomModel> {
    return this.apiUploadUploadPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UploadFileModelResultCustomModel>): UploadFileModelResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUploadUploadPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUploadUploadPost$Json$Response(params?: ApiUploadUploadPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadFileModelResultCustomModel>> {
    return apiUploadUploadPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUploadUploadPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUploadUploadPost$Json(params?: ApiUploadUploadPost$Json$Params, context?: HttpContext): Observable<UploadFileModelResultCustomModel> {
    return this.apiUploadUploadPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UploadFileModelResultCustomModel>): UploadFileModelResultCustomModel => r.body)
    );
  }

}
