/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponseResultCustomModel } from '../../models/product-response-result-custom-model';

export interface ApiProductGetProductByIdGet$Plain$Params {
  productId?: number;
}

export function apiProductGetProductByIdGet$Plain(http: HttpClient, rootUrl: string, params?: ApiProductGetProductByIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiProductGetProductByIdGet$Plain.PATH, 'get');
  if (params) {
    rb.query('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponseResultCustomModel>;
    })
  );
}

apiProductGetProductByIdGet$Plain.PATH = '/api/Product/GetProductById';
