/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCategoryRequestListResultCustomModel } from '../../models/create-category-request-list-result-custom-model';

export interface ApiProductGetCategorysGet$Plain$Params {
}

export function apiProductGetCategorysGet$Plain(http: HttpClient, rootUrl: string, params?: ApiProductGetCategorysGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateCategoryRequestListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiProductGetCategorysGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateCategoryRequestListResultCustomModel>;
    })
  );
}

apiProductGetCategorysGet$Plain.PATH = '/api/Product/GetCategorys';
