/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CheckPromotionModel } from '../../models/check-promotion-model';
import { PromotionResponseResultCustomModel } from '../../models/promotion-response-result-custom-model';

export interface ApiPromotionCheckPromotionCodePost$Json$Params {
      body?: CheckPromotionModel
}

export function apiPromotionCheckPromotionCodePost$Json(http: HttpClient, rootUrl: string, params?: ApiPromotionCheckPromotionCodePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PromotionResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiPromotionCheckPromotionCodePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromotionResponseResultCustomModel>;
    })
  );
}

apiPromotionCheckPromotionCodePost$Json.PATH = '/api/Promotion/CheckPromotionCode';
