/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PromotionResponseListResultCustomModel } from '../../models/promotion-response-list-result-custom-model';

export interface ApiPromotionListPromotionGet$Json$Params {
}

export function apiPromotionListPromotionGet$Json(http: HttpClient, rootUrl: string, params?: ApiPromotionListPromotionGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PromotionResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiPromotionListPromotionGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromotionResponseListResultCustomModel>;
    })
  );
}

apiPromotionListPromotionGet$Json.PATH = '/api/Promotion/ListPromotion';
