/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PromotionResponseResultCustomModel } from '../../models/promotion-response-result-custom-model';

export interface ApiPromotionGetPromotionByIdPromotionCodeGet$Plain$Params {
  promotionCode: string;
}

export function apiPromotionGetPromotionByIdPromotionCodeGet$Plain(http: HttpClient, rootUrl: string, params: ApiPromotionGetPromotionByIdPromotionCodeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PromotionResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiPromotionGetPromotionByIdPromotionCodeGet$Plain.PATH, 'get');
  if (params) {
    rb.path('promotionCode', params.promotionCode, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PromotionResponseResultCustomModel>;
    })
  );
}

apiPromotionGetPromotionByIdPromotionCodeGet$Plain.PATH = '/api/Promotion/GetPromotionById/{promotionCode}';
