/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateOrderRequest } from '../../models/create-order-request';
import { Int32ResultCustomModel } from '../../models/int-32-result-custom-model';

export interface ApiOrderCreatePost$Json$Params {
      body?: CreateOrderRequest
}

export function apiOrderCreatePost$Json(http: HttpClient, rootUrl: string, params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiOrderCreatePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Int32ResultCustomModel>;
    })
  );
}

apiOrderCreatePost$Json.PATH = '/api/Order/Create';
