/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetListOrderSpResultListResultCustomModel } from '../../models/get-list-order-sp-result-list-result-custom-model';

export interface ApiOrderListOrderGet$Json$Params {
}

export function apiOrderListOrderGet$Json(http: HttpClient, rootUrl: string, params?: ApiOrderListOrderGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListOrderSpResultListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiOrderListOrderGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetListOrderSpResultListResultCustomModel>;
    })
  );
}

apiOrderListOrderGet$Json.PATH = '/api/Order/ListOrder';
